# Generated by Django 4.2.7 on 2024-01-19 19:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
                ('apellido', models.CharField(max_length=80)),
                ('fecha', models.DateField()),
                ('motivo_rechazo', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Automotriz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='servicio_autos')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono_cliente', models.CharField(default='+569', help_text='Ingrese el número de teléfono chileno &#x1F1E8;&#x1F1F1 🐧', max_length=12)),
                ('correo_usuario', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='Ingrese una dirección de correo electrónico válida.')])),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('email', models.EmailField(default='@', max_length=254, validators=[django.core.validators.EmailValidator(message='Ingrese una dirección de correo electrónico válida.')])),
                ('telefono', models.CharField(default='+569', help_text='Ingrese un número de teléfono Chileno Válido. &#x1F1E8;&#x1F1F1 🐧', max_length=12)),
                ('tipo_contacto', models.IntegerField(choices=[[0, 'Sugerencia'], [1, 'Reclamo']])),
                ('mensaje', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
                ('segundo_nombre', models.CharField(max_length=70)),
                ('apellido', models.CharField(max_length=70)),
                ('segundo_apellido', models.CharField(max_length=70)),
                ('rut', models.CharField(default='1-0', max_length=70)),
                ('fecha_nacimiento', models.DateField(null=True)),
                ('numero_telefono', models.IntegerField(null=True)),
                ('email', models.EmailField(default='@', max_length=254, validators=[django.core.validators.EmailValidator(message='Ingrese una dirección de correo electrónico válida.')])),
                ('foto', models.ImageField(null=True, upload_to='Curriculums/')),
                ('experiencia', models.TextField(max_length=2000)),
                ('especialidad', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='Trabajos/')),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Mecanico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(default='1-0', max_length=70)),
                ('nombre', models.CharField(max_length=70)),
                ('edad', models.IntegerField(default=0)),
                ('apellido', models.CharField(max_length=80)),
                ('email', models.EmailField(default='example@example.com', max_length=254)),
                ('especialista', models.CharField(default='Sin especialidad', max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('foto', models.ImageField(null=True, upload_to='Mecanico/')),
                ('descripcion', models.CharField(default='0', max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Motos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='servicio_motos')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pintura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('imagen_antes', models.ImageField(default='ruta/a/tu/imagen_default_antes.jpg', upload_to='servicio_pintura')),
                ('imagen_despues', models.ImageField(default='ruta/a/tu/imagen_default_despues.jpg', upload_to='servicio_pintura')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publicidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='publicidad/')),
                ('descripcion', models.TextField()),
                ('enlace', models.URLField(blank=True, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('prioridad', models.PositiveIntegerField(default=0)),
                ('max_ancho', models.PositiveIntegerField(default=0, help_text='Ancho máximo en píxeles para la imagen')),
                ('max_alto', models.PositiveIntegerField(default=0, help_text='Alto máximo en píxeles para la imagen')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('correo_usuario', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='Ingrese una dirección de correo electrónico válida.')])),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('apellido_cliente', models.CharField(max_length=100)),
                ('telefono_cliente', models.CharField(default='+569', help_text='Ingrese el número de teléfono chileno &#x1F1E8;&#x1F1F1 🐧', max_length=12)),
                ('tipo_vehiculo', models.CharField(choices=[('auto', 'Auto'), ('moto', 'Moto')], max_length=20)),
                ('marca_vehiculo', models.CharField(max_length=50)),
                ('modelo_vehiculo', models.CharField(max_length=50)),
                ('informacion_adicional', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Restauracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('imagen_antes', models.ImageField(upload_to='restauraciones/antes/')),
                ('imagen_despues', models.ImageField(upload_to='restauraciones/despues/')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('imagenes', models.ImageField(null=True, upload_to='Trabajos/')),
                ('autorizado', models.BooleanField(default=False)),
                ('categoria', models.CharField(choices=[('Mantencion', 'Mantencion'), ('Reparacion', 'Reparacion'), ('Diagnostico', 'Diagnostico')], default='Mantencion', max_length=20)),
                ('mecanico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appweb.mecanico')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen_producto', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appweb.categoria')),
                ('marca', models.ForeignKey(blank=True, limit_choices_to={'nombre__in': ['Vistony', 'Hyundai', 'Shell', 'Super Mobil']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appweb.marca')),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pagada', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('carrito', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appweb.carrito')),
            ],
        ),
        migrations.CreateModel(
            name='ItemCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appweb.carrito')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appweb.producto')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion_entrega', models.TextField()),
                ('costo_envio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comuna', models.CharField(max_length=50)),
                ('retiro_local', models.BooleanField(default=False)),
                ('metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appweb.metodopago')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appweb.orden')),
            ],
        ),
        migrations.AddField(
            model_name='carrito',
            name='productos',
            field=models.ManyToManyField(through='appweb.ItemCarrito', to='appweb.producto'),
        ),
    ]
