# Generated by Django 4.2.7 on 2024-01-20 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='telefono_cliente',
        ),
        migrations.AddField(
            model_name='detalleorden',
            name='telefono_cliente',
            field=models.CharField(default='+569', help_text='Ingrese el número de teléfono chileno &#x1F1E8;&#x1F1F1 🐧', max_length=12),
        ),
    ]
