# Generated by Django 4.2.1 on 2024-01-20 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0002_remove_carrito_telefono_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=0, default='0', max_digits=10),
        ),
    ]
