# Generated by Django 4.2.7 on 2024-01-23 16:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0004_alter_producto_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='telefono_cliente',
            field=models.CharField(default='+569', help_text='Ingrese el número de teléfono chileno &#x1F1E8;&#x1F1F1 🐧', max_length=12, validators=[django.core.validators.MinLengthValidator(limit_value=12, message='El número de teléfono debe tener al menos 12 caracteres.')]),
        ),
    ]
