# Generated by Django 4.2.7 on 2024-01-23 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0005_alter_reserva_telefono_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleorden',
            name='metodo_pago',
        ),
        migrations.RemoveField(
            model_name='detalleorden',
            name='orden',
        ),
        migrations.RemoveField(
            model_name='itemcarrito',
            name='carrito',
        ),
        migrations.RemoveField(
            model_name='itemcarrito',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='carrito',
        ),
        migrations.DeleteModel(
            name='Carrito',
        ),
        migrations.DeleteModel(
            name='DetalleOrden',
        ),
        migrations.DeleteModel(
            name='ItemCarrito',
        ),
        migrations.DeleteModel(
            name='MetodoPago',
        ),
        migrations.DeleteModel(
            name='Orden',
        ),
    ]
