# Generated by Django 4.2.7 on 2024-01-23 20:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0006_remove_detalleorden_metodo_pago_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(default='+569', help_text='Ingrese el número de teléfono chileno 🐧', max_length=12, validators=[django.core.validators.MinLengthValidator(limit_value=12, message='El número de teléfono debe tener al menos 12 caracteres.')])),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='Ingrese una dirección de correo electrónico válida.')])),
                ('comuna', models.CharField(max_length=255)),
            ],
        ),
    ]
