# Generated by Django 4.2.1 on 2024-01-25 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0007_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='metodo_entrega',
            field=models.CharField(choices=[('retiro_local', 'Retiro en local'), ('despacho', 'Despacho a domicilio')], default='despacho', max_length=20),
        ),
    ]
