# Generated by Django 4.2.7 on 2024-01-27 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0010_carrito_alter_producto_marca_productoencarrito_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='comuna',
            field=models.CharField(blank=True, choices=[('puente_alto', 'Puente Alto'), ('otra', 'Otra')], default='Otra', max_length=255, null=True),
        ),
    ]
