# Generated by Django 5.0.3 on 2024-03-20 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0011_alter_cliente_comuna'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mecanico',
            options={'verbose_name_plural': 'Administrar Mecanicos'},
        ),
    ]
