# Generated by Django 5.0.3 on 2024-03-20 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0012_alter_mecanico_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='productos',
        ),
        migrations.RemoveField(
            model_name='productoencarrito',
            name='carrito',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='productoencarrito',
            name='producto',
        ),
        migrations.AlterModelOptions(
            name='automotriz',
            options={'verbose_name_plural': 'Administrar Fotos Servicio Automotriz'},
        ),
        migrations.AlterModelOptions(
            name='motos',
            options={'verbose_name_plural': 'Administrar Fotos Servicio de Motos'},
        ),
        migrations.AlterModelOptions(
            name='pintura',
            options={'verbose_name_plural': 'Administrar Fotos Servicio de Pintura'},
        ),
        migrations.AlterModelOptions(
            name='publicidad',
            options={'verbose_name_plural': 'Administrar Imagenes Home/Principal'},
        ),
        migrations.AlterModelOptions(
            name='reserva',
            options={'verbose_name_plural': 'Administrar Reservas'},
        ),
        migrations.AlterModelOptions(
            name='restauracion',
            options={'verbose_name_plural': 'Administrar Fotos Servicio de Restauración'},
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Carrito',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Marca',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.DeleteModel(
            name='ProductoEnCarrito',
        ),
    ]
