# Generated by Django 5.0.3 on 2024-03-20 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0013_remove_carrito_cliente_remove_carrito_productos_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacto',
            options={'verbose_name_plural': 'Administrar Contacto de clientes web'},
        ),
    ]
