# Generated by Django 5.0.3 on 2024-03-21 00:19

import appweb.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0015_alter_mecanico_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicidad',
            name='imagen',
            field=models.ImageField(upload_to=appweb.models.path_and_rename),
        ),
    ]
