# Generated by Django 5.0.3 on 2024-03-21 00:29

import appweb.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0016_alter_publicidad_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicidad',
            options={'verbose_name_plural': 'Administrar Imágenes Home/Principal'},
        ),
        migrations.AlterField(
            model_name='mecanico',
            name='foto',
            field=models.ImageField(null=True, upload_to=appweb.models.path_and_rename),
        ),
    ]
