# Generated by Django 5.0.3 on 2024-03-23 19:11

import appweb.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0024_alter_mecanico_foto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mecanico',
            options={},
        ),
        migrations.AddField(
            model_name='contacto',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='mecanico',
            name='foto',
            field=models.ImageField(null=True, upload_to=appweb.models.path_and_rename),
        ),
    ]
